var a = parseInt(prompt("Enter a no.","0"),10);
document.write("Result");
document.write("<br />");
document.write("The value of a is: " + a);
document.write("<br />");
document.write("---------------------------------");
document.write("<br />");
document.write("<br />");
document.write("The value of ++a is: " + ++a);
document.write("<br />");
document.write("Now the value of a is: " + a);
document.write("<br />");
document.write("<br />");
document.write("The value of a++ is: " + a++);
document.write("<br />");
document.write("Now the value of a is: " + a);
document.write("<br />");
document.write("<br />");
document.write("The value of --a is: " + --a);
document.write("<br />");
document.write("Now the value of a is: " + a);
document.write("<br />");
document.write("<br />");
document.write("The value of a-- is: " + a--);
document.write("<br />");
document.write("Now the value of a is: " + a);
document.write("<br />");
document.write("<br />");